# ===============================================================
# DEFAULT PROFILE (for local development)
# ===============================================================
spring:
  application:
    name: audiance-backend

  profiles:
    active: ${SPRING_PROFILE:local}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:audiancedb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Resets DB on each start, perfect for local dev
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            scope: user-read-email, user-read-private, user-top-read, playlist-modify-public, playlist-modify-private
            authorization-grant-type: authorization_code
            redirect-uri: ${FRONTEND_URL:http://localhost:3000}/auth/callback
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me

# Custom Application Properties
app:
  fastapi:
    url: ${FASTAPI_URL:http://localhost:8000}
    timeout: 30000

  jwt:
    secret: ${JWT_SECRET:dummy-local-jwt-secret-for-dev-use-only-12345}
    expiration: 86400000 # 24 hours

  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

  spotify:
    api-url: https://api.spotify.com/v1
    accounts-url: https://accounts.spotify.com/api
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    top-artists-cache-hours: 24 # Cache user's top artists for 24 hours

  ai:
    model: meta-llama/Llama-3.1-8B-Instruct
    huggingface-token: ${HUGGINGFACE_TOKEN}
    story-mode-threshold: 100 # Word count threshold for story vs direct mode
    max-scenes: 6 # Maximum scenes per story

  # Available genre options for user selection
  app:
    available-genres: # YAML list (use hyphens for array)
      - hip-hop
      - rnb
      - pop
      - afrobeats
      - dance
      - indie
      - rock
      - electronic
      - jazz
      - soul

  # Playlist generation settings
  playlist:
    min-tracks-per-scene: 3
    max-tracks-per-scene: 10
    default-tracks-per-scene: 5
    max-total-tracks: 50

# IMPORTANT: This default encryption key is for local development ONLY.
# It MUST be overridden by a secure 16-character environment variable in production.
audiance:
  security:
    encryptor-key: ${ENCRYPTOR_KEY:local_encryptkey}

# Server Configuration
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

# Logging
logging:
  level:
    com.audience: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    org.springframework.web: DEBUG

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

---
# ===============================================================
# PRODUCTION PROFILE
# ===============================================================
spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update # Safe for prod: applies changes without dropping data
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc.lob.non_contextual_creation: true # Helps with Postgres Lob handling

  h2:
    console:
      enabled: false

server:
  error:
    include-message: never
    include-binding-errors: never

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.audience: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: INFO

# Production overrides
app:
  ai:
    story-mode-threshold: 80 # Slightly lower in prod for better UX